local Theme = {}

Theme.layout = { cols = 6, rows = 12, padding = 2, bgcolor = WHITE }

Theme.boxes = {
  { col = 1, row = 1, colspan = 2, rowspan = 3, type = "time", subtype = "flight", title = "@i18n(widgets.dashboard.flight_duration)@", titlepos = "bottom", title_offset_y = 4, title_offset_y_lowres = 7, bgcolor = BLACK, titlecolor = COLOR_THEME_DISABLED, textcolor = WHITE },
  { col = 3, row = 1, colspan = 2, rowspan = 3, type = "text", subtype = "stats", stattype = "max", source = "throttle_percent", unit = "%", transform = "floor", title = "@i18n(widgets.dashboard.throttle_max)@", titlepos = "bottom", title_offset_y = 3, title_offset_y_lowres = 6, bgcolor = BLACK, titlecolor = COLOR_THEME_DISABLED, textcolor = WHITE },
  { col = 5, row = 1, colspan = 2, rowspan = 3, type = "text", subtype = "stats", stattype = "max", source = "smartconsumption", unit = "mAh", transform = "floor", title = "@i18n(widgets.dashboard.consumed_mah)@", titlepos = "bottom", title_offset_y = 3, title_offset_y_lowres = 6, bgcolor = BLACK, titlecolor = COLOR_THEME_DISABLED, textcolor = WHITE },
  { col = 1, row = 4, colspan = 2, rowspan = 3, type = "time", subtype = "total", title = "@i18n(widgets.dashboard.total_flight_duration)@", titlepos = "bottom", title_offset_y = 3, title_offset_y_lowres = 6, bgcolor = BLACK, titlecolor = COLOR_THEME_DISABLED, textcolor = WHITE },
  { col = 3, row = 4, colspan = 2, rowspan = 3, type = "text", subtype = "stats", stattype = "max", source = "current", unit = "A", transform = "floor", title = "@i18n(widgets.dashboard.current_max)@", titlepos = "bottom", title_offset_y = 3, title_offset_y_lowres = 6, bgcolor = BLACK, titlecolor = COLOR_THEME_DISABLED, textcolor = WHITE },
  { col = 5, row = 4, colspan = 2, rowspan = 3, type = "text", subtype = "stats", stattype = "min", source = "smartfuel", unit = "%", transform = "floor", title = "@i18n(widgets.dashboard.fuel_remaining)@", titlepos = "bottom", title_offset_y = 3, title_offset_y_lowres = 6, bgcolor = BLACK, titlecolor = COLOR_THEME_DISABLED, textcolor = WHITE },
  { col = 1, row = 7, colspan = 2, rowspan = 3, type = "text", subtype = "stats", stattype = "max", source = "rpm", unit = " rpm", transform = "floor", title = "@i18n(widgets.dashboard.rpm_max)@", titlepos = "bottom", title_offset_y = 3, title_offset_y_lowres = 6, bgcolor = BLACK, titlecolor = COLOR_THEME_DISABLED, textcolor = WHITE },
  { col = 3, row = 7, colspan = 2, rowspan = 3, type = "text", subtype = "stats", stattype = "max", source = "esc_temp", unit = "C", transform = "floor", title = "@i18n(widgets.dashboard.esc_max_temp)@", titlepos = "bottom", title_offset_y = 3, title_offset_y_lowres = 6, bgcolor = BLACK, titlecolor = COLOR_THEME_DISABLED, textcolor = WHITE },
  { col = 5, row = 7, colspan = 2, rowspan = 3, type = "text", subtype = "stats", source = "min_voltage_cell", title = "@i18n(widgets.dashboard.min_volts_cell)@", titlepos = "bottom", title_offset_y = 3, title_offset_y_lowres = 6, bgcolor = BLACK, titlecolor = COLOR_THEME_DISABLED, textcolor = WHITE },
  { col = 1, row = 10, colspan = 2, rowspan = 3, type = "text", subtype = "stats", stattype = "max", source = "watts", unit = "W", transform = "floor", title = "@i18n(widgets.dashboard.watts_max)@", titlepos = "bottom", title_offset_y = 3, title_offset_y_lowres = 6, bgcolor = BLACK, titlecolor = COLOR_THEME_DISABLED, textcolor = WHITE },
  { col = 3, row = 10, colspan = 2, rowspan = 3, type = "text", subtype = "stats", source = "min_link", title = "@i18n(widgets.dashboard.lq)@", titlepos = "bottom", title_offset_y = 3, title_offset_y_lowres = 6, bgcolor = BLACK, titlecolor = COLOR_THEME_DISABLED, textcolor = WHITE },
  { col = 5, row = 10, colspan = 2, rowspan = 3, type = "text", subtype = "stats", stattype = "last", source = "voltage", unit = "V", decimals = 2, title = "@i18n(widgets.dashboard.volts_per_cell)@", titlepos = "bottom", title_offset_y = 3, title_offset_y_lowres = 6, bgcolor = BLACK, titlecolor = COLOR_THEME_DISABLED, textcolor = WHITE }
}

return Theme
